// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBP7OAHb_YFoOliF2sDh-XL88OvYk4dTTc',
    appId: '1:697803531622:web:7a4930d285d79505e514a7',
    messagingSenderId: '697803531622',
    projectId: 'flutter-test-7e8f6',
    authDomain: 'flutter-test-7e8f6.firebaseapp.com',
    storageBucket: 'flutter-test-7e8f6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBehXa58diQSU0z88pZss_5KOnLTB6MnpM',
    appId: '1:697803531622:android:98a4cbfb8ab8a35de514a7',
    messagingSenderId: '697803531622',
    projectId: 'flutter-test-7e8f6',
    storageBucket: 'flutter-test-7e8f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8yiqIMED2oLn4BdC30TWKaJE6D2MaEU0',
    appId: '1:697803531622:ios:f53727e39014e998e514a7',
    messagingSenderId: '697803531622',
    projectId: 'flutter-test-7e8f6',
    storageBucket: 'flutter-test-7e8f6.appspot.com',
    iosClientId: '697803531622-sahn3s8b9itu7j8kgfu6u7p05euqgkc6.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8yiqIMED2oLn4BdC30TWKaJE6D2MaEU0',
    appId: '1:697803531622:ios:f53727e39014e998e514a7',
    messagingSenderId: '697803531622',
    projectId: 'flutter-test-7e8f6',
    storageBucket: 'flutter-test-7e8f6.appspot.com',
    iosClientId: '697803531622-sahn3s8b9itu7j8kgfu6u7p05euqgkc6.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication4',
  );
}
